springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.application.name=finastorage


spring.data.mongodb.uri=${MONGODB_URI}

spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.database=fina-db

server.port=8080
server.servlet.context-path=/api

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.web=INFO